: SQ DUP * ;
: CR 10 EMIT ;

: MARK    DP 0 , ;
: RESOLVE DP OVER - SWAP ! ;

: IF   ['] JZ  C, MARK ; IMMEDIATE
: ELSE ['] JMP C, MARK SWAP RESOLVE ; IMMEDIATE
: THEN RESOLVE ; IMMEDIATE   
: BEGIN DP ; IMMEDIATE
: UNTIL ['] JZ  C, DP - , ; IMMEDIATE
: AGAIN ['] JMP C, DP - , ; IMMEDIATE
: WHILE ['] JZ C, MARK ; IMMEDIATE
: REPEAT SWAP ['] JMP C, DP - , RESOLVE ; IMMEDIATE

: ( BEGIN KEY 41 = UNTIL ; IMMEDIATE

: CASE 0 ; IMMEDIATE

: 2DUP OVER OVER ;
: 2DROP DROP DROP ;
: FACTORIAL
  1 2 ROT
  BEGIN
      2DUP <=
  WHILE
      -ROT TUCK
      * SWAP
      1 + ROT
  REPEAT
  2DROP ;

ENTRY

2 3 < IF
  3 SQ 1 + . CR
  5 FACTORIAL . CR
ELSE
  ( shouldn't  be executed )
  65 EMIT
THEN

BYE

