: SQ DUP * ;
: CR 10 EMIT ;

: MARK    DP 0 , ;
: RESOLVE DP OVER - SWAP ! ;
: IF      ['] JZ  C, MARK ; IMMEDIATE
: ELSE    ['] JMP C, MARK SWAP RESOLVE ; IMMEDIATE
: THEN    RESOLVE ; IMMEDIATE
: BEGIN   DP ; IMMEDIATE
: UNTIL   ['] JZ  C, DP - , ; IMMEDIATE
: AGAIN   ['] JMP C, DP - , ; IMMEDIATE
: WHILE   ['] JZ C, MARK ; IMMEDIATE
: REPEAT  SWAP ['] JMP C, DP - , RESOLVE ; IMMEDIATE

: ( BEGIN KEY 41 = UNTIL ; IMMEDIATE

: CASE 0 ; IMMEDIATE
: OF
  ['] OVER C, ['] = C,
  ['] JZ   C, MARK
  ['] DROP C,
; IMMEDIATE

: ENDOF
    SWAP 1 + SWAP
    ['] JMP C, MARK SWAP
    RESOLVE
    SWAP
; IMMEDIATE

: ENDCASE
  BEGIN
    DUP 0 >
  WHILE
    1 - SWAP RESOLVE
  REPEAT
  DROP
; IMMEDIATE

: 2DUP OVER OVER ;
: 2DROP DROP DROP ;
: FACTORIAL
  1 2 ROT
  BEGIN
      2DUP <=
  WHILE
      -ROT TUCK
      * SWAP
      1 + ROT
  REPEAT
  2DROP ;

: CHOOSE
  CASE
    1 OF 10 ENDOF
    2 OF 20 ENDOF
    3 OF 30 ENDOF
    DROP 99
  ENDCASE ;

ENTRY

2 3 < IF
  3 SQ 1 + . CR
  5 FACTORIAL . CR
ELSE
  ( shouldn't  be executed )
  65 EMIT
THEN

2 CHOOSE . CR
3 CHOOSE . CR
7 CHOOSE . CR

DEPTH . CR

BYE
