#!/bin/bash

IMAGE="compiler.img"
COMPILER="compiler.forth"
TEST="test/smoke.forth"

rm -f "$IMAGE"

python bootstrap.py "$COMPILER" "$IMAGE"

./warp -m "$IMAGE" < "$TEST"
./warp -m "$IMAGE"

rm -f "$IMAGE"
