#!/bin/bash

COMPILER=stage2.img
OUTPUT=output.img
LIB="lib.forth"
INPUT="/dev/stdin"

if [[ -n "$1" && -f "$1" ]]; then
  INPUT="$1"
else
  echo "Usage compile <file.forth>"
  exit 1
fi

rm -f "$OUTPUT"

echo "Compiling $1.."
cat "$LIB"   \
    "$INPUT" \
    | ./warp "$COMPILER"

echo "Running compiled image: $OUTPUT"
./warp "$OUTPUT"
